### ISSUE TITLE
The module's dependencies are incompatible with Magento 2.3.x

### ISSUE THREAD

**Issue by djacques4gorilla** [snowio/magento2-lock#6]
With Magento 2.1 reaching EOL in June and 2.2 in December, Magento applications need to be upgraded to 2.3, but the extension's current Composer dependencies exclude that version (the magento/framework major version is now 102 and the dependency is for 100 or 101). The dependencies should be updated and the module tested (and possibly adjusted as needed) to support Magento 2.3.x.

**Comment by darryla** [comment]
Hi there, this issue is now resolved in v1.3.0

https://github.com/snowio/magento2-lock/tree/v1.3.0
